language: node_js

node_js:
  - '20'

addons:
  sonarcloud:
    organization: 'armonkahil'
    token:
      secure: 'REPLACE_WITH_ENCRYPTED_SONAR_TOKEN'

cache:
  npm: true

install:
  - npm ci

script:
  - npm run test:coverage
  - sonar-scanner
